site_name: Oliver's Handbook
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Roboto
    code: Red Hat Mono
  palette: 
    # Light Mode
    - scheme: default
      toggle: 
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue grey
      accent: deep orange

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: deep purple